springdoc:
  swagger-ui:
    path: '/'

server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/todolist?serverTimezone=UTC
#    username: root
#    password: root
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      pool-name: Hikari
      auto-commit: false
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
