spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 8
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
