springdoc:
  swagger-ui:
    path: '/swagger'


server:
  port: ${PORT:8081}

spring:
  profiles:
    active: dev
    include:
      - swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/todolist?serverTimezone=UTC
#    username: root
#    password: root
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      pool-name: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: DEBUG
    by.palgogo.todolist: DEBUG

